apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-osd
  labels:
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-mgr
  labels:
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-cmd-reporter
  labels:
    {{- include "rook-ceph-cluster.labels" . | nindent 4 }}
